# Generated by Django 5.1.1 on 2024-09-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_number_rows', models.IntegerField()),
                ('all_number_armchairs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ArmChair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_row', models.IntegerField()),
                ('number_armchair', models.IntegerField()),
                ('hall_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_for_cinema.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('film_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_for_cinema.film')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type_ticket', models.CharField(max_length=20)),
                ('price_info', models.DecimalField(decimal_places=2, max_digits=10)),
                ('armchair_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_for_cinema.armchair')),
                ('seance_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_for_cinema.seance')),
                ('user_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_for_cinema.user')),
            ],
        ),
    ]
