# Generated by Django 5.1.1 on 2024-09-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_for_cinema', '0002_seance_hall_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='armchair',
            name='number_hall',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
